/* This file was generated by syncqt. */
#ifndef QT_QTGIFIMAGE_VERSION_H
#define QT_QTGIFIMAGE_VERSION_H

#define QTGIFIMAGE_VERSION_STR "0.1.0"

#define QTGIFIMAGE_VERSION 0x000100

#endif // QT_QTGIFIMAGE_VERSION_H
